package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/caboose-mcp/waldo/internal/export"
)

func main() {
	flag.Parse()

	// Get current working directory (project root)
	projectRoot, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to get working directory: %v\n", err)
		os.Exit(1)
	}

	// Load waldo config
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to get home directory: %v\n", err)
		os.Exit(1)
	}

	personasDir := filepath.Join(home, ".config", "waldo", "personas")
	activeFile := filepath.Join(personasDir, ".active")

	// Read active persona
	activeData, err := os.ReadFile(activeFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ No active persona found. Run: waldo use agent/default\n")
		os.Exit(1)
	}

	activeName := strings.TrimSpace(string(activeData))
	personaPath := filepath.Join(personasDir, activeName+".meml")

	// Read persona file
	personaData, err := os.ReadFile(personaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Persona file not found: %s\n", personaPath)
		os.Exit(1)
	}

	// Convert MEML to Cursor workspace rules format
	cursorRules := memlToCursorRules(string(personaData), activeName)

	// Write .cursorrules file in project root
	cursorRulesPath := filepath.Join(projectRoot, ".cursorrules")
	if err := os.WriteFile(cursorRulesPath, []byte(cursorRules), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to write .cursorrules: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Synced persona '%s' to %s\n", activeName, cursorRulesPath)
}

// memlToCursorRules converts a MEML persona to Cursor workspace rules format.
// Cursor rules are Markdown-based and placed in .cursorrules file.
func memlToCursorRules(memlContent string, personaName string) string {
	persona, err := export.ParseMEML(memlContent)
	if err != nil {
		// Fallback to minimal template if parsing fails
		return fmt.Sprintf("# Cursor Rules — waldo persona: %s\n\n# (Could not parse persona: %v)\n", personaName, err)
	}

	// Use ChatGPTExporter to generate markdown system prompt
	exporter := &export.ChatGPTExporter{Persona: persona}
	prompt := exporter.SystemPrompt()

	rules := fmt.Sprintf(`# Cursor Rules — Generated by waldo
# Persona: %s

%s
`,
		personaName, prompt)

	return rules
}
