package export

import (
	"fmt"
	"strings"
)

// ZedExporter generates Zed-compatible AI rules from a persona.
// Zed's AI Agent Panel reads a `.rules` file from the project root
// and injects it verbatim as a system prompt.
type ZedExporter struct {
	Persona *PersonaConfig
}

// SystemPrompt generates a plain-text system prompt for Zed.
// Uses the same structure as GeminiExporter (no markdown bold).
func (ze *ZedExporter) SystemPrompt() string {
	p := ze.Persona

	tone := fmt.Sprintf(`Tone Settings:
- Formality: %.1f (0=very casual, 1=very formal)
- Directness: %.1f (0=roundabout, 1=blunt)
- Humor: %.1f (0=dry, 1=frequent wit)
- Hedging: %.1f (0=confident, 1=heavily qualified)
- Warmth: %.1f (0=cold, 1=enthusiastic)`,
		p.Tone.Formality, p.Tone.Directness, p.Tone.Humor, p.Tone.Hedging, p.Tone.Warmth)

	verbosity := fmt.Sprintf(`Verbosity:
- Response length: %s
- Reading level: %s
- Format preference: %s`,
		p.Verbosity.ResponseLength, p.Verbosity.ReadingLevel, p.Verbosity.FormatPreference)

	voice := fmt.Sprintf(`Voice:
- Avoid: %s
- Prefer: %s
- Characteristic phrases: %s`,
		strings.Join(p.Voice.AvoidWords, ", "),
		strings.Join(p.Voice.PreferWords, ", "),
		strings.Join(p.Voice.CustomPhrases, ", "))

	prompt := fmt.Sprintf(`You are designed to respond with this personality profile:

%s

%s

%s

Apply these traits consistently to all your responses.`,
		tone, verbosity, voice)

	return prompt
}

// RulesFile returns the complete .rules file content for Zed.
// This is written to .rules in the project root.
func (ze *ZedExporter) RulesFile() string {
	header := fmt.Sprintf(`# Zed Rules — Generated by waldo
# Persona: %s
# Source: ~/.config/waldo/personas/%s.meml
# Update with: waldo-zed-sync

`,
		ze.Persona.Name, ze.Persona.Name)

	return header + ze.SystemPrompt()
}

// Markdown returns a formatted markdown version suitable for documentation.
func (ze *ZedExporter) Markdown() string {
	return fmt.Sprintf(`# %s

%s

## System Prompt

%s`, ze.Persona.Name, ze.Persona.Description, ze.SystemPrompt())
}

// Instructions returns Zed-specific instruction format.
func (ze *ZedExporter) Instructions() string {
	return fmt.Sprintf(`Copy this into Zed's .rules file at your project root:

%s

---

How to use:
1. Run waldo-zed-sync from your project root
2. Open the Zed AI Agent Panel (cmd-shift-c or similar)
3. The persona will be active for all AI interactions in this project

To update:
- Run waldo-zed-sync again
- The .rules file will be refreshed with the latest persona

`, ze.RulesFile())
}
